version: '3.8'

services:
  frontend:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "4001:4001"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000/api/v1
      - PORT=4001
    command: sh -c "npm install && npm run dev -- -p 4001"
    stdin_open: true
    tty: true