name: 🐛 Bug Report
description: Report a bug to help us improve
title: '[BUG] '
labels: ['bug']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Type
      description: What type of bug is this?
      options:
        - Frontend (UI/UX issues)
        - Backend (API/Server issues)
        - Fullstack (Cross-boundary issues)
        - Infrastructure (Deployment/DevOps)
    validations:
      required: true

  - type: markdown
    attributes:
      value: |

        ---

        **Bug Details**

  - type: input
    id: bug-title
    attributes:
      label: Bug Title
      description: A clear and concise title for the bug
      placeholder: 'e.g., Product images not loading on mobile devices'
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: 'Describe the bug in detail...'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |

        ---

        **Reproduction & Behavior**

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: 'Describe what should happen...'
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: 'Describe what actually happened...'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |

        ---

        **Environment Information**

  - type: input
    id: browser
    attributes:
      label: Browser (Frontend bugs)
      description: Which browser are you using?
      placeholder: 'Chrome, Firefox, Safari, Edge'
    validations:
      required: false

  - type: input
    id: device
    attributes:
      label: Device (Frontend bugs)
      description: What device are you using?
      placeholder: 'iPhone 14, MacBook Pro, Windows PC'
    validations:
      required: false

  - type: input
    id: api-endpoint
    attributes:
      label: API Endpoint (Backend bugs)
      description: Which API endpoint is affected?
      placeholder: 'GET /api/products, POST /api/orders'
    validations:
      required: false

  - type: markdown
    attributes:
      value: |

        ---

        **Additional Information**

  - type: textarea
    id: error-message
    attributes:
      label: Error Message
      description: Any error messages or stack traces
      placeholder: 'Paste error messages here...'
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: 'Screenshots, logs, environment details...'
    validations:
      required: false
